
import java.awt.Color;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Enrico Tomasi
 */
public class GUI extends javax.swing.JFrame 
{
    int TextStatus = 0;
    int TextFieldStatus = 0;
    
    Message message = new Message();
    
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Appliication_Panel = new javax.swing.JPanel();
        Info = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonsPanel = new javax.swing.JPanel();
        OpenButton = new javax.swing.JButton();
        EncodeButton = new javax.swing.JButton();
        DecodeButton = new javax.swing.JButton();
        SavePanel = new javax.swing.JPanel();
        SavePath = new javax.swing.JLabel();
        KeyNameField = new javax.swing.JPanel();
        KeyNameTextField = new javax.swing.JTextField();
        MessagePanel_Base = new javax.swing.JPanel();
        MessagePanel = new javax.swing.JScrollPane();
        Message = new javax.swing.JTextArea();
        CounterPanel = new javax.swing.JPanel();
        TitleNum = new javax.swing.JLabel();
        Counter = new javax.swing.JLabel();
        KeyNameLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FProtocol");
        setBounds(new java.awt.Rectangle(0, 0, 1366, 768));
        setName("FPROTOCOL"); // NOI18N

        Appliication_Panel.setLayout(null);

        Info.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Created: 25/11/2019  ©Enrico Tomasi ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("VERSION 1.0");

        javax.swing.GroupLayout InfoLayout = new javax.swing.GroupLayout(Info);
        Info.setLayout(InfoLayout);
        InfoLayout.setHorizontalGroup(
            InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(InfoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        InfoLayout.setVerticalGroup(
            InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
        );

        Appliication_Panel.add(Info);
        Info.setBounds(1060, 590, 300, 130);

        ButtonsPanel.setAlignmentX(0.0F);
        ButtonsPanel.setAlignmentY(0.0F);
        ButtonsPanel.setMaximumSize(new java.awt.Dimension(280, 260));
        ButtonsPanel.setOpaque(false);
        ButtonsPanel.setLayout(null);

        OpenButton.setBackground(new java.awt.Color(235, 166, 29));
        OpenButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        OpenButton.setText("OPEN MESSAGE");
        OpenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OpenButtonMousePressed(evt);
            }
        });
        ButtonsPanel.add(OpenButton);
        OpenButton.setBounds(170, 130, 240, 80);

        EncodeButton.setBackground(new java.awt.Color(149, 255, 113));
        EncodeButton.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        EncodeButton.setText("ENCODE!");
        EncodeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EncodeButtonMouseClicked(evt);
            }
        });
        EncodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncodeButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(EncodeButton);
        EncodeButton.setBounds(0, 0, 280, 110);

        DecodeButton.setBackground(new java.awt.Color(47, 169, 235));
        DecodeButton.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        DecodeButton.setText("DECODE!");
        DecodeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DecodeButtonMouseClicked(evt);
            }
        });
        ButtonsPanel.add(DecodeButton);
        DecodeButton.setBounds(309, 0, 270, 110);

        Appliication_Panel.add(ButtonsPanel);
        ButtonsPanel.setBounds(460, 490, 580, 210);

        SavePanel.setOpaque(false);

        SavePath.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SavePath.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout SavePanelLayout = new javax.swing.GroupLayout(SavePanel);
        SavePanel.setLayout(SavePanelLayout);
        SavePanelLayout.setHorizontalGroup(
            SavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SavePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SavePath, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                .addContainerGap())
        );
        SavePanelLayout.setVerticalGroup(
            SavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SavePath, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Appliication_Panel.add(SavePanel);
        SavePanel.setBounds(290, 720, 920, 40);

        KeyNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        KeyNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeyNameTextFieldMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KeyNameTextFieldMousePressed(evt);
            }
        });
        KeyNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeyNameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KeyNameFieldLayout = new javax.swing.GroupLayout(KeyNameField);
        KeyNameField.setLayout(KeyNameFieldLayout);
        KeyNameFieldLayout.setHorizontalGroup(
            KeyNameFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KeyNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        KeyNameFieldLayout.setVerticalGroup(
            KeyNameFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KeyNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Appliication_Panel.add(KeyNameField);
        KeyNameField.setBounds(460, 440, 580, 40);

        Message.setColumns(20);
        Message.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        Message.setLineWrap(true);
        Message.setRows(5);
        Message.setText("<Inserire qui il messaggio da cifrare>");
        Message.setToolTipText("");
        Message.setWrapStyleWord(true);
        Message.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MessageMouseClicked(evt);
            }
        });
        Message.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MessageKeyTyped(evt);
            }
        });
        MessagePanel.setViewportView(Message);

        javax.swing.GroupLayout MessagePanel_BaseLayout = new javax.swing.GroupLayout(MessagePanel_Base);
        MessagePanel_Base.setLayout(MessagePanel_BaseLayout);
        MessagePanel_BaseLayout.setHorizontalGroup(
            MessagePanel_BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MessagePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        MessagePanel_BaseLayout.setVerticalGroup(
            MessagePanel_BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MessagePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        Appliication_Panel.add(MessagePanel_Base);
        MessagePanel_Base.setBounds(180, 20, 1130, 410);

        CounterPanel.setOpaque(false);
        CounterPanel.setLayout(null);

        TitleNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TitleNum.setForeground(new java.awt.Color(232, 35, 74));
        TitleNum.setText("NUMERO CARATTERI:");
        CounterPanel.add(TitleNum);
        TitleNum.setBounds(0, 10, 160, 30);

        Counter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Counter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Counter.setToolTipText("");
        CounterPanel.add(Counter);
        Counter.setBounds(10, 50, 130, 40);

        Appliication_Panel.add(CounterPanel);
        CounterPanel.setBounds(10, 20, 160, 150);

        KeyNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        KeyNameLabel.setText("NOME DELLA CHIAVE");
        Appliication_Panel.add(KeyNameLabel);
        KeyNameLabel.setBounds(240, 450, 210, 22);

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.jpg"))); // NOI18N
        Background.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Background.setPreferredSize(new java.awt.Dimension(1024, 768));
        Appliication_Panel.add(Background);
        Background.setBounds(0, -50, 1366, 820);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Appliication_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Appliication_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        Appliication_Panel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MessageMouseClicked
        SavePath.setText("");
        
        Message.setForeground(Color.BLACK);
        
        if(TextStatus == 0)
        {
            Message.setText("");
            TextStatus = 1;
        }
        
        Counter.setText(""+Message.getText().length()+"");
    }//GEN-LAST:event_MessageMouseClicked

    private void KeyNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeyNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeyNameTextFieldActionPerformed

    private void OpenButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenButtonMousePressed
        try {
            SavePath.setText("");
            
            message.Load();
            Message.setText(message.message);
            
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OpenButtonMousePressed

    private void KeyNameTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeyNameTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeyNameTextFieldMousePressed

    private void KeyNameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeyNameTextFieldMouseClicked
        SavePath.setText("");
        
        if(TextFieldStatus == 0)
        {
            KeyNameTextField.setText("");
            TextFieldStatus = 1;
        }
    }//GEN-LAST:event_KeyNameTextFieldMouseClicked

    private void EncodeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncodeButtonMouseClicked

            String key;
            
            if(TextFieldStatus == 0)
            {
                key = "";
                TextFieldStatus = 1;
                KeyNameTextField.setText("");
            }
            else
            {
                key = KeyNameTextField.getText();
                KeyNameTextField.setText("");
            }
            
            String text = Message.getText();
            message.write(text);
            message.encode(key);
            text = message.read();
            Message.setText(text);
            
            message.Save();
            
            SavePath.setText("MESSAGGIO SALVATO IN: "+System.getProperty("user.dir"));
    }//GEN-LAST:event_EncodeButtonMouseClicked

    private void DecodeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecodeButtonMouseClicked
        String Guess = KeyNameTextField.getText();
        
        int decoding = message.decode(Guess);
        
        if(decoding == -1)
        {
            Message.setForeground(Color.red);
            Message.setText("ACCESSO AL MESSAGGIO NEGATO! RIPROVARE");
        }
        else
        {
            Message.setText(message.message);
        }
    }//GEN-LAST:event_DecodeButtonMouseClicked

    private void EncodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncodeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EncodeButtonActionPerformed

    private void MessageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MessageKeyTyped
        Counter.setText(""+(Message.getText().length()+1)+"");
    }//GEN-LAST:event_MessageKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Appliication_Panel;
    private javax.swing.JLabel Background;
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JLabel Counter;
    private javax.swing.JPanel CounterPanel;
    private javax.swing.JButton DecodeButton;
    private javax.swing.JButton EncodeButton;
    private javax.swing.JPanel Info;
    private javax.swing.JPanel KeyNameField;
    private javax.swing.JLabel KeyNameLabel;
    private javax.swing.JTextField KeyNameTextField;
    private javax.swing.JTextArea Message;
    private javax.swing.JScrollPane MessagePanel;
    private javax.swing.JPanel MessagePanel_Base;
    private javax.swing.JButton OpenButton;
    private javax.swing.JPanel SavePanel;
    private javax.swing.JLabel SavePath;
    private javax.swing.JLabel TitleNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
